# Generated by Django 5.0.4 on 2025-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour_license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessidentitystructure',
            name='number_of_employees',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
