# Generated by Django 5.0.4 on 2025-07-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employeesalarydetails_is_variable_bonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='deduction_type',
            new_name='deduction_name',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='payslip_name',
        ),
        migrations.AddField(
            model_name='deduction',
            name='calculation_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='deduction',
            name='component_type',
            field=models.CharField(default='Fixed', max_length=60),
        ),
        migrations.AddField(
            model_name='deduction',
            name='includes_epf_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='includes_esi_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmployeeCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_credentials', to='payroll.employeemanagement')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('check_in_type', models.CharField(choices=[('manual', 'Manual'), ('geo', 'Geo Location'), ('face', 'Face Recognition'), ('qr', 'QR Code'), ('timesheet', 'Timesheet'), ('biometric', 'Biometric Device'), ('auto', 'System Auto')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('device_info', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='payroll.employeecredentials')),
            ],
        ),
    ]
