# Generated by Django 5.0.4 on 2025-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_rename_deduction_type_deduction_deduction_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='bonus_incentive',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='monthly_fixed_tds',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='other_deductions_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="List of {'component_name': 'Name', 'amount': 500}"),
        ),
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='other_earnings_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="List of dictionaries with 'component_name' and 'amount'"),
        ),
        migrations.AddField(
            model_name='pt',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)')], default='O+', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='epf',
            name='admin_charge_in_ctc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epf',
            name='allow_employee_level_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epf',
            name='apply_components_if_wage_below_15k',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epf',
            name='employee_contribution_rate',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='epf',
            name='employer_contribution_rate',
            field=models.CharField(default=None, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='epf',
            name='epf_number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='epf',
            name='include_employer_contribution_in_ctc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epf',
            name='prorate_restricted_pf_wage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='esi',
            name='employee_contribution',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='esi',
            name='employer_contribution',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='esi',
            name='esi_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
