# Generated by Django 5.0.4 on 2025-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_employeesalaryhistory_bonus_incentive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollworkflow',
            name='lock_payroll',
            field=models.BooleanField(default=False),
        ),
    ]
