# Generated by Django 5.0.4 on 2025-08-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_alter_employeemanagement_employee_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_birthday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_to', models.ManyToManyField(blank=True, related_name='events_applicable_to', to='payroll.worklocations')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_birthday', to='payroll.employeemanagement')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payroll.payrollorg')),
            ],
        ),
    ]
