# Generated by Django 5.0.4 on 2025-08-26 07:07

import payroll.helpers
import usermanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_eventmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducationdetails',
            name='upload_certificate',
            field=models.FileField(blank=True, null=True, storage=usermanagement.models.PrivateS3Storage(), upload_to=payroll.helpers.employee_education_certificate),
        ),
    ]
