# Generated by Django 5.0.4 on 2025-07-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymanagerialpersonnel',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
